on:
  push:
    branches:
      - master

name: Build and Publish
jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'no-ci')"
    name: Build Library
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@v1
      with:
        node-version: 16.18.1
    - uses: actions/cache@v1
      id: cache-modules
      with:
        path: node_modules
        key: ${{ runner.OS }}-build-${{ hashFiles('package.json') }}
    - run: yarn install --pure-lockfile
      if: steps.cache-modules.outputs.cache-hit != 'true'
    - run: yarn build
    - run: yarn test
    - run: yarn test:badges
    - name: Upload esm build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-esm
        path: esm
    - name: Upload lib build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build-lib
        path: lib
